---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  pull: default
  image: timovibritannia/ansible
  commands:
  - ansible-lint ./

---
kind: pipeline
name: publish

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master
  event:
  - tag

steps:
- name: prepare-tests
  pull: default
  image: timovibritannia/ansible
  commands:
  - chmod +x ci.sh
  - chmod +x ci-tag.sh
  - chmod +x ci-ssh.sh
  - export DRONE_COMMIT=$(curl -sL https://api.github.com/repos/mailcow/mailcow-dockerized/commits/master | jq -r '.sha')
  - export DRONE_GIT_HTTP_URL=https://github.com/mailcow/mailcow-dockerized.git
  - ./ci.sh
  - ./ci-tag.sh
  - wget -O group_vars/all/secrets.yml $SECRETS_DOWNLOAD_URL --quiet
  environment:
    SECRETS_DOWNLOAD_URL:
      from_secret: SECRETS_DOWNLOAD_URL
    VAULT_PW:
      from_secret: VAULT_PW
  when:
    branch:
    - master
    event:
    - tag

- name: create-server
  pull: default
  image: timovibritannia/ansible
  commands:
  - ansible-playbook mailcow-start-server.yml --diff
  - ./ci-ssh.sh
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
    ANSIBLE_FORCE_COLOR: true
  when:
    branch:
    - master
    event:
    - tag

- name: setup-server
  pull: default
  image: timovibritannia/ansible
  commands:
  - sleep 120
  - ansible-playbook mailcow-setup-server.yml --private-key /drone/src/id_ssh_rsa --diff
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
    ANSIBLE_FORCE_COLOR: true
  when:
    branch:
    - master
    event:
    - tag

- name: run-tests
  pull: default
  image: timovibritannia/ansible
  commands:
  - ansible-playbook mailcow-integration-tests.yml --private-key /drone/src/id_ssh_rsa --diff
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
    ANSIBLE_FORCE_COLOR: true
  when:
    branch:
    - master
    event:
    - tag

- name: delete-server
  pull: default
  image: timovibritannia/ansible
  commands:
  - ansible-playbook mailcow-delete-server.yml --diff
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
    ANSIBLE_FORCE_COLOR: true
  when:
    branch:
    - master
    event:
    - tag
    status:
    - failure
    - success

- name: update-changelog
  pull: default
  image: node:latest
  commands:
  - npm ci
  - npm run verion
  when:
    branch:
    - master
    event:
    - tag

- name: create-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_API_KEY
    title: ${DRONE_TAG}
    note: CHANGELOG.md
    overwrite: true
  when:
    branch:
    - master
    event:
    - tag

---
kind: signature
hmac: 3e7fb424b83015131511f4598701799fab27c179f2b0e5e637ef74030beb5e51

...
