---
- name: Setup Server
  hosts: all
  gather_facts: true
  become: yes
  roles:
    - role: cloud-init
      tags: [ 'cloud-init' ]
    - role: self-shutdown
      tags: [ 'self-shutdown' ]
    - role: apt-updates
      tags: [ 'apt-updates' ]
    - role: apt-requierments
      tags: [ 'apt-requierments' ]
    - role: pip-requierments
      tags: [ 'pip-requierments' ]
    - role: npm-requierments
      tags: [ 'npm-requierments' ]
    - role: cloudflare-dns
      tags: [ 'cloudflare-dns' ]
    - role: netplan
      tags: [ 'netplan' ]
    - role: docker-ce
      tags: [ 'docker-ce' ]
    - role: docker-compose
      tags: [ 'docker-compose' ]
    - role: verify-dns
      tags: [ 'verify-dns' ]
    - role: mailcow
      tags: [ 'mailcow' ]
