---

- name: Install nodejs
  become: yes
  apt:
    name: nodejs
    state: present

- name: Install npm
  become: yes
  apt:
    name: npm
    state: present

- name: Install jsonlint
  become: yes
  npm:
      name: jsonlint
      global: true
      state: present

- name: Install html-minifier
  become: yes
  npm:
      name: html-minifier
      global: true
      state: present
