---

- name: Stop mailcow container stack
  become: yes
  shell: docker-compose down
  args:
    chdir: /opt/mailcow-dockerized

- name: Remove docker volumes
  become: yes
  community.general.docker_prune:
    volumes: yes

- name: Start mailcow container stack
  become: yes
  shell: docker-compose up -d
  args:
    chdir: /opt/mailcow-dockerized

- name: Wait 120 seconds before starting tests
  wait_for:
    timeout: 120
  delegate_to: localhost
