---

- name: Get OS infos
  import_tasks: infos/os.yml

- name: Run admin password change tests
  import_tasks: tests/admin_password.yml

- name: Run domain creation tests
  import_tasks: tests/domain.yml

- name: Run mailbox creation tests
  import_tasks: tests/mailbox.yml

- name: Run DKIM creation tests
  import_tasks: tests/dkim.yml

- name: Run email sending and rspamd tests
  import_tasks: tests/sendmail.yml

- name: Run app password tests
  import_tasks: tests/app_password.yml

- name: Run syncjob tests
  import_tasks: tests/syncjob.yml

- name: Run langauge coverage tests
  import_tasks: tests/lang_coverage.yml

- name: Run oAuth apps tests
  import_tasks: tests/oauth_apps.yml

- name: Run domain policy tests
  import_tasks: tests/domain_policy.yml

- name: Run ratelimit tests
  import_tasks: tests/ratelimit.yml

- name: Run fowarding hosts tests
  import_tasks: tests/forwarding_hosts.yml

- name: Run alias tests
  import_tasks: tests/alias.yml

- name: Run domain admin tests
  import_tasks: tests/domain_admin.yml

- name: Run netfilter tests
  import_tasks: tests/netfilter.yml

- name: Run sieve prefilter tests
  import_tasks: tests/sieve_prefilter.yml

- name: Run sieve prefilter redirect tests
  import_tasks: tests/sieve_prefilter_redirect.yml

- name: Run watchdog tests
  import_tasks: tests/watchdog.yml

- name: Run logs tests
  import_tasks: tests/logs.yml

- name: Generate report mailcow.email
  import_tasks: reports/generate_mailcowemail.yml

- name: Final arragation
  import_tasks: reports/final_arragation.yml
