---

- name: "Create a record for {{ mailcow__hostname }}"
  community.general.cloudflare_dns:
    zone: "{{ mailcow__dns_zone }}"
    record: "{{ mailcow__hostname_local_part }}"
    type: A
    value: "{{ ansible_default_ipv4.address }}"
    api_token: "{{ vault__cloudflare__apitoken }}"

- name: "Create aaaa record for {{ mailcow__hostname }}"
  community.general.cloudflare_dns:
    zone: "{{ mailcow__dns_zone }}"
    record: "{{ mailcow__hostname_local_part }}"
    type: AAAA
    value: "{{ ansible_default_ipv6.address }}"
    api_token: "{{ vault__cloudflare__apitoken }}"

- name: "Create mx record for {{ mailcow__hostname }}"
  community.general.cloudflare_dns:
    zone: "{{ mailcow__dns_zone }}"
    record: "{{ mailcow__test_domain_local_part }}"
    priority: 10
    type: MX
    value: "{{ mailcow__hostname }}"
    api_token: "{{ vault__cloudflare__apitoken }}"
