---

- name: "Create a record for {{ mailcow__hostname }}"
  cloudflare_dns:
    zone: "{{ mailcow__dns_zone }}"
    record: "{{ mailcow__hostname_local_part }}"
    type: A
    value: "{{ ansible_default_ipv4.address }}"
    account_email: "{{ vault__cloudflare__email }}"
    account_api_token: "{{ vault__cloudflare__apikey }}"

- name: "Create aaaa record for {{ mailcow__hostname }}"
  cloudflare_dns:
    zone: "{{ mailcow__dns_zone }}"
    record: "{{ mailcow__hostname_local_part }}"
    type: AAAA
    value: "{{ ansible_default_ipv6.address }}"
    account_email: "{{ vault__cloudflare__email }}"
    account_api_token: "{{ vault__cloudflare__apikey }}"

- name: "Create mx record for {{ mailcow__hostname }}"
  cloudflare_dns:
    zone: "{{ mailcow__dns_zone }}"
    record: "{{ mailcow__test_domain_local_part }}"
    priority: 10
    type: MX
    value: "{{ mailcow__hostname }}"
    account_email: "{{ vault__cloudflare__email }}"
    account_api_token: "{{ vault__cloudflare__apikey }}"
